import mongoose from "mongoose";

const paymentSchema = new mongoose.Schema({
  id: String,
  order_number: String,
  order_amount: Number,
  order_currency: String,
  order_description: String,
  order_status: String,
  type: String,
  status: String,
  payment_status: String,
  reason: { type: String, default: "" },
  payee_name: { type: String, default: "" },
  payee_email: { type: String, default: "" },
  payee_country: { type: String, default: "" },
  payee_state: { type: String, default: "" },
  payee_city: { type: String, default: "" },
  payee_address: { type: String, default: "" },
  rrn: { type: String, default: "" },
  approval_code: { type: String, default: "" },
  card: { type: String, default: "" },
  card_expiration_date: { type: String, default: "" },
  payee_card: { type: String, default: "" },
  card_token: { type: String, default: "" },
  customer_name: { type: String, default: "" },
  customer_email: { type: String, default: "" },
  customer_country: { type: String, default: "" },
  customer_state: { type: String, default: "" },
  customer_city: { type: String, default: "" },
  customer_address: { type: String, default: "" },
  customer_ip: String,
  date: Date,
  recurring_init_trans_id: { type: String, default: "" },
  recurring_token: { type: String, default: "" },
  schedule_id: { type: String, default: "" },
  exchange_rate: { type: Number, default: 0 },
  exchange_rate_base: { type: Number, default: 0 },
  exchange_currency: {},
  exchange_amount: { type: Number, default: 0 },
  vat_amount: { type: Number, default: 0 },
  hash: String,
});

export default mongoose.models.Payment ||
  mongoose.model("Payment", paymentSchema);
